### PR TITLE
Increase proc compatibility (ampersand and triple-equal)

### PR DESCRIPTION
**Pull request by rewritten**
This will allow constructs like
```rb
data.then(&MyService).tap(&MySideEffects)
```

and

```rb
case data
when MyValidator.new(**some_config), MyOtherValidator
  :ok
when MyValidator
  :so_and_so
else
  :nope
end
```

### CODE REVIEW

**Comment by rewritten** [comment]
Maybe overriding the _class_ method `:===` is too invasive, as this would break:
```rb
case my_service_instance
when MyServiceClass
  :something
when MyOtherServiceClass
  :something_else
else
  nil
end
```

Although, I don't see why one would branch on a service instance type...

**Comment by rewritten** [comment]
Procs also respond to square-brackets:
```rb
my_proc = ->(str) { str.upcase }
my_proc['asdf']
# => "ASDF"
```
but I know no one that uses it.

**Comment by rewritten** [comment]
Hold your horses, this will not work with inheritance (`alias` is scoped to the definition scope)

**Comment by iovis** [comment]
Hey man, thanks again for the proposal!

Unfortunately I’m currently sick so it might take me a few days to come back to you, sorry about that!

**Comment by Papipo** [comment]
I like the proc thingy, not so sure about the triple equals, but still, I think that it would be better to implement those in separate PRs.

**Comment by iovis** [comment]
> Hey man, thanks again for the proposal!
> 
> Unfortunately I’m currently sick so it might take me a few days to come back to you, sorry about that!

Haven't forgotten about these, I'm very sorry for the wait. I finally recovered this week but I have some stuff that has piled on because of that downtime and has kept me from taking a look at these. I want to take a good look at all of these!

Also, hi @Papipo! 👋

**Comment by Papipo** [comment]
Hi @iovis 👋 . Maybe you got sick because you had to go to the office?

**Comment by iovis** [comment]
No office for us for a while haha

**Pull request closed without merging**
