### PR TITLE
Override with class

### PR DESCRIPTION
**Pull request by Papipo**
This PR builds on top of #27

It allows you to pass a class instead of an instance to `new`, and `Injectable` takes care of instantiating it for you.

Our use case is an `AppContainer` injectable that defines defaults and we want to be able to override those when we extend our engine.

### CODE REVIEW

**Comment by Papipo** [comment]
I hate you, coudclaimet.

**Comment by Papipo** [comment]
@rewritten aren't you no longer using `Injectable` or just don't have time/interest?

**Comment by rewritten** [comment]
@Papipo I'm no longer using Injectable, so I cannot dedicate much effort to improve it.

**Comment by Papipo** [comment]
@rewritten can I ask why? did you implement something better yourself or found a better alternative? Thanks!

**Comment by rewritten** [comment]
@Papipo in general, I have some disagreement on the feature set and architecture, and I prefer to roll my own callable objects using ActiveModel and/or dry-rb tools, depending on the maturity of the corresponding codebase.

Specifically there are three features that prevent me to use Injectable and to be interested in advancing it:
1. Expilcitly forbidding inheritance: Although I see the point in not hiding code, superclasses can serve as templates for common behavior and I use them extensively. There was a working PR that provided correct support for inheritance and it's still open.
2. Dependency injection: The only way to inject a different dependency than the predefined one is to interact with the constructor. This goes against all my knowledge of DI, where the responsibility of injecting a dependency is not on the caller, but on a global container that can be configured per-environment or per-request etc.
3. Not passing arguments to the constructor: There is no way to have a service object get the arguments and then inspect it in a test, because args are only passed to the `call` method. Therefore tests can only be on the SO result, and I cannot write stuff like `it { is_expected.to allow_value('red').for(:color) }` (this one is from shoulda_matchers gem)

**Comment by Papipo** [comment]
@rewritten

I think I saw that inheritance PR and felt very complex to attain the feature. If my last PRs get merged, maybe it will be easier now that the dependencies proxy is gone? Although i tend to use object collaboration rather than inheritance.

regarding no. 2, I am working on a rails engine that has an `AppContainer` injectable that allows for different dependencies to be injected. In fact that's how we override features in the paid version of it.

Can you provide a use case for no. 3? Is it just for testing?

**Comment by rewritten** [comment]
> I think I saw that inheritance PR and felt very complex to attain the feature. If my last PRs get merged, maybe it will be easier now that the dependencies proxy is gone? Although i tend to use object collaboration rather than inheritance.

I agree that collaboration should be preferred to cover different use cases, but inheritance is king when defining abstract superclasses that have a common shape and purpose (renderable objects, command objects, transformer objects, …) with no common pattern except for general architecture. Anyway, I don't see the point of _forbidding_ inheritance (except because the current implementation is incompatible with subclassing).

> regarding no. 2, I am working on a rails engine that has an `AppContainer` injectable that allows for different dependencies to be injected. In fact that's how we override features in the paid version of it.

That's cool. I had no idea that there was a paid version of it.

> 
> Can you provide a use case for no. 3? Is it just for testing?

Not just for testing. It feels very surprising to me (and other developers) that `call` gets no arguments, but still these arguments (passed with `instance.call(**args)`) are available as instance accessors inside the call method. It kind of breaks my expectations on how objects work.

We can still have a nice proc-like interface without prepending anything, just by defining
```rb
def self.call(**args) = new(**args).call
```
This will make the whole implementation much simpler and understandable.

**Comment by rewritten** [comment]
BTW years ago I was talking with Matz, about forking vs contributing, and he was adamant: reuse and contribute to mainstream project unless they are so incompatible that your eyes bleed at the very thought of using them (like ActiveSupport's effect to some people).

Therefore, I want to point you to the great and quite well supported [`dry-rb`](https://dry-rb.org/) gem family, with which you can achieve essentially 100% of my desired feature set + 100% of the existing feature set, using `dry-initializer`, `dry-container` and `dry-auto-inject` (with an already existing engine at `dry-rails` and a completely independent application container with baked-in DI at `dry-system`).

**Comment by Papipo** [comment]
> That's cool. I had no idea that there was a paid version of it.

Sorry for the misunderstanding. It's the project I am working on that has a paid version, not injectable 😅 
> 
> Not just for testing. It feels very surprising to me (and other developers) that `call` gets no arguments, but still these arguments (passed with `instance.call(**args)`) are available as instance accessors inside the call method. It kind of breaks my expectations on how objects work.

Yes, that's quite opinionated indeed.

**Pull request closed without merging**
