### PR TITLE
Introduce Ruby Actions for CI

### PR DESCRIPTION
**Pull request by jantequera**
Issue #9 

I used one of the starter actions available in GH Actions to set up the gem and run the specs.

Check out the successful checks section to see that it works

### CODE REVIEW

**Comment by iovis** [comment]
This is awesome! Could we make it so it runs the specs on the PR as well?

**Comment by jantequera** [comment]
@iovis I think that's how it works already. Check the build: https://github.com/rubiconmd/injectable/pull/14/checks?check_run_id=510628533

**Comment by jantequera** [comment]
Let me look into it

**Comment by jantequera** [comment]
By looking at the docs and the trace I'd say it works by default on PRs that target master

Captura de pantalla 2020-03-16 a las 13 40 04
Captura de pantalla 2020-03-16 a las 13 39 23

It would be weird if it ran the specs against the master branch when opening a PR against it, instead that on the branch that makes the changes

**Comment by iovis** [comment]
To be honest, if it didn't work like that probably this action wouldn't have run till we merged to master. 
I need more coffee.

**Pull request merged**
